### PR TITLE
Basic API implementation

### PR DESCRIPTION
**Pull request by DavidePrincipi**
APIs to manage initial module setup, user and public mailboxes, mail domains, and addresses

- get-configuration
- list-domains
- add-domain / alter-domain / remove-domain
- list-addresses
- add-address / remove-address / alter-address
- list-destinations
- list-user-mailboxes
- alter-user-mailbox (custom quota, forwards, custom spam retention)
- add-public-mailbox
- alter-public-mailbox
- list-acl-subjects
- list-public-mailboxes
- remove-public-mailbox

Add also
- Postfix implementation of LDAP group members expansion
- Postfix user forward addresses

### CODE REVIEW

**Review by gsanchietti — COMMENTED** [review]
This is way too hard to review.
Just a question: what is stored inside sqlite database?

**Comment by DavidePrincipi** [comment]
> what is stored inside sqlite database?

Good question! The answer should be here https://github.com/NethServer/ns8-mail/blob/f4143fe55b91e68d134fd9524a5731283a11e1f8/postfix/README.md#data-tables

But it seems I forgot to add some tables, I'm adding them.

**Comment by gsanchietti** [comment]
> > what is stored inside sqlite database?
> 
> Good question! The answer should be here https://github.com/NethServer/ns8-mail/blob/f4143fe55b91e68d134fd9524a5731283a11e1f8/postfix/README.md#data-tables
> 
> But it seems I forgot to add some tables, I'm adding them.

Ok, so the whole configuration as I thought.

Fine for me.
You can merge, we will see what will break :)

**Comment by DavidePrincipi** [comment]
> Ok, so the whole configuration as I thought.

Not exactly IMO. Postfix configuration/data is stored both in the DB and in the environment variables.

Dovecot configuration/data is stored in environment variables and Dovecot "dict" databases. They are accessible by Dovecot HTTP API.

In the old times ns[67], everything was in the e-smith DB :)

**Pull request merged**
